#!/usr/bin/env python3
"""Measure the Chenile code base and its documentation; writes _data/codebase.yml.

Usage (from the site repo):  python3 scripts/codebase-stats.py [path-to-framework-folder]
The framework folder is the parent directory holding the 11 repository checkouts
(default: the site repo's parent). Re-run after a release to refresh /by-the-numbers/.

Counting rules
- Java: non-blank lines that are not comments; Javadoc (/** ... */) counted separately.
  Files under src/test/ count as test code.
- Front end: non-blank .js/.jsx/.ts/.tsx/.css/.vue lines (excludes node_modules, dist).
- Maven modules: number of pom.xml files.
- Ignored directories: target, node_modules, dist, build, .git, site-resources, IDE folders.
"""
import datetime, glob, os, re, subprocess, sys

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FRAMEWORK = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else os.path.dirname(SITE)
REPOS = ["chenile-parent", "chenile-core", "chenile-query-workflow-blueprints", "chenile-process-management",
         "chenile-service-registry", "chenile-proxies", "chenile-security", "chenile-messaging",
         "chenile-bdd", "chenile-others", "cconfig"]
TOOLING = ["chenile-gen"]
SKIP = {"target", "node_modules", "dist", "build", ".git", "site-resources", ".idea", ".vscode", "out",
        ".mvn", "coverage", ".jgen-portal", "test-results"}
FRONT = {"js", "jsx", "ts", "tsx", "css", "vue"}


def java_lines(path):
    code = doc = 0; block = isdoc = False
    for line in open(path, encoding="utf-8", errors="ignore"):
        s = line.strip()
        if not s:
            continue
        if block:
            doc += isdoc
            if "*/" in s: block = False
            continue
        if s.startswith("/**"):
            doc += 1; block, isdoc = "*/" not in s[3:], True; continue
        if s.startswith("/*"):
            block, isdoc = "*/" not in s[2:], False; continue
        if s.startswith("//"):
            continue
        code += 1
    return code, doc


def measure(repo):
    st = dict(modules=0, main_files=0, main_loc=0, test_files=0, test_loc=0, javadoc=0, features=0,
              feature_lines=0, frontend_loc=0, config_files=0, templates=0, md_files=0, md_words=0)
    for dp, dn, fn in os.walk(os.path.join(FRAMEWORK, repo)):
        dn[:] = [d for d in dn if d not in SKIP]
        for f in fn:
            p = os.path.join(dp, f); ext = f.rsplit(".", 1)[-1].lower() if "." in f else ""
            if ext == "java":
                c, d = java_lines(p); t = "test" if f"{os.sep}src{os.sep}test{os.sep}" in p else "main"
                st[f"{t}_files"] += 1; st[f"{t}_loc"] += c; st["javadoc"] += d
            elif f == "pom.xml": st["modules"] += 1
            elif ext == "feature":
                st["features"] += 1; st["feature_lines"] += sum(1 for l in open(p, errors="ignore") if l.strip())
            elif ext in FRONT:
                st["frontend_loc"] += sum(1 for l in open(p, errors="ignore") if l.strip())
            elif ext in ("xml", "json", "yml", "yaml", "properties", "sql"): st["config_files"] += 1
            elif ext == "mustache": st["templates"] += 1
            elif ext == "md":
                st["md_files"] += 1; st["md_words"] += len(open(p, errors="ignore").read().split())
    try:
        st["commits"] = int(subprocess.run(["git", "-C", os.path.join(FRAMEWORK, repo), "rev-list", "--count", "HEAD"],
                                           capture_output=True, text=True).stdout.strip() or 0)
    except Exception:
        st["commits"] = 0
    return st


def site_words(pattern):
    files = glob.glob(os.path.join(SITE, pattern)); w = 0
    for p in files:
        t = open(p, errors="ignore").read()
        t = re.sub(r"^---.*?---", "", t, flags=re.S)
        t = re.sub(r"<[^>]+>|\{%.*?%\}|\{\{.*?\}\}", " ", t)
        w += len(t.split())
    return len(files), w


repos = {r: measure(r) for r in REPOS if os.path.isdir(os.path.join(FRAMEWORK, r))}
tools = {r: measure(r) for r in TOOLING if os.path.isdir(os.path.join(FRAMEWORK, r))}
tot = {k: sum(v[k] for v in repos.values()) for k in next(iter(repos.values()))}
docs = {}
for label, pat in [("Concept articles", "_concepts/*.md"), ("Developer guides", "pages/developer/*.md"),
                   ("Release notes", "pages/release-notes/*.md"), ("Video episode pages", "_episodes/*.md"),
                   ("Other site pages", "pages/*.md")]:
    docs[label] = site_words(pat)
site_pages = sum(n for n, _ in docs.values()); site_wordcount = sum(w for _, w in docs.values())

out = [f"# Generated by scripts/codebase-stats.py on {datetime.date.today()} — do not edit by hand.",
       f"measured: \"{datetime.date.today():%B %-d, %Y}\"", "repos:"]
for r, s in repos.items():
    out.append(f"  - name: \"{r}\"")
    out += [f"    {k}: {v}" for k, v in s.items()]
out.append("totals:"); out += [f"  {k}: {v}" for k, v in tot.items()]
out.append("tooling:")
for r, s in tools.items():
    out.append(f"  - name: \"{r}\"")
    out += [f"    {k}: {v}" for k, v in s.items()]
out.append("docs:")
for label, (n, w) in docs.items():
    out.append(f"  - {{ label: \"{label}\", pages: {n}, words: {w} }}")
out.append(f"site_pages: {site_pages}"); out.append(f"site_words: {site_wordcount}")
open(os.path.join(SITE, "_data", "codebase.yml"), "w").write("\n".join(out) + "\n")
print(f"11 repos: {tot['main_loc']} main + {tot['test_loc']} test Java lines, {tot['modules']} modules; "
      f"site: {site_pages} pages / {site_wordcount} words → _data/codebase.yml")
